# Generated by Django 4.0.3 on 2022-06-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('Nombre_Cientifico', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombre_Comercial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('MMSI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('VesselName', models.CharField(max_length=30, null=True)),
                ('Matricula', models.CharField(max_length=12, null=True, unique=True)),
                ('Image', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('Timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('Lote', models.CharField(max_length=15)),
                ('Puerto', models.CharField(max_length=30, null=True)),
                ('Zona_Captura', models.CharField(max_length=7, null=True)),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fecha_Fin', models.DateTimeField()),
                ('Nombre_Pez_Bandeja', models.CharField(max_length=20, null=True)),
                ('Kg_Bandeja', models.IntegerField(null=True)),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MatriculaOf', to='webgisapp.vessel', to_field='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Fish_Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Talla_cm', models.IntegerField()),
                ('Cantidad', models.IntegerField(null=True)),
                ('Peso', models.FloatField()),
                ('Lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.plate')),
                ('Nombre_Cientifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.fish')),
            ],
        ),
        migrations.CreateModel(
            name='AISVessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseDateTime', models.DateTimeField()),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
                ('SOG', models.FloatField()),
                ('COG', models.FloatField()),
                ('VesselName', models.CharField(max_length=30, null=True)),
                ('CallSign', models.CharField(max_length=10)),
                ('VesselType', models.IntegerField(null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Length', models.IntegerField(null=True)),
                ('Width', models.IntegerField(null=True)),
                ('Cargo', models.IntegerField(null=True)),
                ('TransceiverClass', models.CharField(max_length=1, null=True)),
                ('MMSI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MMSIOf', to='webgisapp.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AIS_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.aisvessel')),
                ('Plate_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.plate')),
                ('Vessel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.vessel')),
            ],
            options={
                'unique_together': {('Vessel_fk', 'AIS_fk', 'Plate_fk')},
            },
        ),
    ]
