# Generated by Django 4.0.3 on 2022-06-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish_plate',
            name='Cantidad',
        ),
    ]
