# Generated by Django 4.0.3 on 2022-04-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISVessel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('BaseDateTime', models.DateField()),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
                ('SOG', models.FloatField()),
                ('COG', models.FloatField()),
                ('VesselName', models.CharField(max_length=30, null=True)),
                ('CallSign', models.CharField(max_length=10)),
                ('VesselType', models.IntegerField(null=True)),
                ('Status', models.IntegerField(null=True)),
                ('Length', models.IntegerField(null=True)),
                ('Width', models.IntegerField(null=True)),
                ('Cargo', models.IntegerField(null=True)),
                ('TransceiverClass', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('MMSI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('VesselName', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='aisvessel',
            name='MMSI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.vessel'),
        ),
    ]
