# Generated by Django 4.0.3 on 2022-06-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0002_remove_fish_plate_cantidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish_plate',
            old_name='Lote',
            new_name='Plate',
        ),
    ]
