# Generated by Django 4.0.3 on 2022-05-04 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0003_alter_aisvessel_basedatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='Matricula',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aisvessel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('Lote', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Puerto', models.CharField(max_length=30, null=True)),
                ('Zona_Captura', models.CharField(max_length=7, null=True)),
                ('Fecha_Inicio', models.DateTimeField()),
                ('Fecha_Fin', models.DateTimeField()),
                ('Nombre_Pez_Bandeja', models.CharField(max_length=20, null=True)),
                ('Kg_Bandeja', models.IntegerField(null=True)),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.vessel', to_field='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Fish_Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Cientifico', models.CharField(max_length=20)),
                ('Talla_cm', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Peso', models.IntegerField(null=True)),
                ('Lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.plate')),
            ],
        ),
    ]
