# Generated by Django 4.0.3 on 2022-06-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0003_rename_lote_fish_plate_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish_plate',
            name='Talla_cm',
            field=models.FloatField(),
        ),
    ]
