# Generated by Django 4.0.3 on 2022-08-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0004_alter_fish_plate_talla_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='KG',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Travel_Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KG', models.FloatField(null=True)),
                ('Nombre_Cientifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.fish')),
                ('Travel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.travel')),
            ],
        ),
    ]
