# Generated by Django 4.0.3 on 2022-05-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0004_vessel_matricula_alter_aisvessel_id_plate_fish_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AIS_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.aisvessel')),
                ('Plate_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.plate')),
                ('Vessel_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.vessel')),
            ],
            options={
                'unique_together': {('Vessel_fk', 'AIS_fk', 'Plate_fk')},
            },
        ),
    ]
