# Generated by Django 4.0.3 on 2022-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0005_salidas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Salidas',
            new_name='Travels',
        ),
    ]
