# Generated by Django 4.0.3 on 2022-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0006_rename_salidas_travels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('Nombre_Cientifico', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Nombre_Comercial', models.CharField(max_length=30)),
            ],
        ),
    ]
