# Generated by Django 4.0.3 on 2022-05-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0007_fish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travels',
            new_name='Travel',
        ),
        migrations.AlterField(
            model_name='fish_plate',
            name='Nombre_Cientifico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webgisapp.fish'),
        ),
    ]
