# Generated by Django 4.0.3 on 2022-05-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webgisapp', '0009_alter_fish_plate_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisvessel',
            name='MMSI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MMSIOf', to='webgisapp.vessel'),
        ),
        migrations.AlterField(
            model_name='fish_plate',
            name='Lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LoteOf', to='webgisapp.plate'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='Matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MatriculaOf', to='webgisapp.vessel', to_field='Matricula'),
        ),
    ]
